#
# Zabbix user parameters for Linux logical volume management (LVM) monitoring
#
# Copyright (c) 2026 Andras Elso


#
# Get a list of all physical volumes (PV) with all attributes
#
# Returns a JSON array containing all physical volumes and their attributes.
# Data gets parsed from the pvs command output (man 8 pvs), all units are in
# bytes. Numeric string values are automatically converted to numbers via jq.
#
# Output format:
#
# [
#    {
#       "pv_name" : "/dev/sda",
#       "pv_uuid" : "S1qfoV-Jbmw-qjqH-koz3-HEyh-eNme-eHlBe8",
#       "pv_size" : 107374182400,
#       "pv_free" : 1073741824,
#       ...
#    },
#    ...
# ]
#
UserParameter=lvm.pvs,sudo /sbin/pvs --noheadings --nosuffix --units b  --options pv_all  --reportformat json| jq '.report[].pv|walk(if type == "string" then tonumber? // . else . end)'


#
# Get a list of all volume groups (VG) with all attributes
#
# Returns a JSON array containing all volume groups and their attributes.
# Data gets parsed from the vgs command output (man 8 vgs), all units are in
# bytes. Numeric string values are automatically converted to numbers via jq.
#
# Output format:
#
# [
#    {
#       "vg_name" : "vg_example_01",
#       "vg_uuid" : "s83QZR-w6c4-Ngqk-u1fM-STAl-evYq-MLxiN0",
#       "vg_size" : 107374182400,
#       "vg_free" : 1073741824,
#       ...
#    },
#    ...
# ]
#
UserParameter=lvm.vgs,sudo /sbin/vgs --noheadings --nosuffix --units b  --options vg_all  --reportformat json| jq '.report[].vg|walk(if type == "string" then tonumber? // . else . end)'


#
# Get a list of all logical volumes (LV) with all attributes
#
# Returns a JSON array containing all logical volumes and their attributes.
# Data gets parsed from the lvs command output (man 8 lvs), all units are in
# bytes. Numeric string values are automatically converted to numbers via jq.
# The segtype option is included to expose the segment type of each volume.
#
# Output format:
#
# [
#    {
#       "lv_name" : "lv_example_01",
#       "vg_name" : "vg_example_01",
#       "lv_uuid" : "dxi5Hw-Xo2m-SAVi-ypZh-QO4I-krpI-sR3N67",
#       "lv_size" : 10737418240,
#       "segtype" : "linear",
#       ...
#    },
#    ...
# ]
#
UserParameter=lvm.lvs,sudo /sbin/lvs --noheadings --nosuffix --units b  --options lv_all,segtype  --reportformat json| jq '.report[].lv|walk(if type == "string" then tonumber? // . else . end)'
